services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: okdp-keycloak
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--health-enabled", "true"]
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost:9000\\r\\nConnection: close\\r\\n\\r\\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "7080:7080"
      - "7443:7443"
      - "9000:9000"

  keycloak-init:
    image: quay.io/keycloak/keycloak:26.0
    container_name: okdp-keycloak-init
    env_file:
      - .env
    entrypoint:
      - sh
      - /scripts/keycloak-init.sh
    restart: "no"
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts:ro
    links:
      - keycloak
